package com.nibado.example.websocket.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

@Component
@Slf4j
public class TimeSender {
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("HH:mm:ss");
    @Autowired
    private SimpMessagingTemplate broker;

    @Autowired
    public TimeSender(final SimpMessagingTemplate broker) {
        this.broker = broker;
    }

    @Scheduled(fixedRate = 5000)
    public void run() {
        String time = LocalTime.now().format(TIME_FORMAT);

        log.info("Time broadcast: {}", time);
        broker.convertAndSend("/topic/greetings", "Resposta " + getRelatorio());
    }
    
    private String getRelatorio() {
    	return "{\"content\":\"PDF teste\",\"relatorio\":\"JVBERi0xLjUKJeLjz9MKNSAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDkwOD4+c3RyZWFtCnic3VjNcts2EL7zKfZW52AY/yBzU2JVdcb1n2gnM5kcKBNW2bHElqKtPE6eIy/Q5+j44CfovQAl0z+ySCigLhkNRQy5iw+7++1iwb+Dd3HAJIRYQpwG/Tg4DSh8sE8JYPOz/yGnEE+CvV8JEAzxVbDzJv7Tyj6KYLicPFWiRgsrpKKFIgVCrCKuXhfjYOf87Hxw3juAg5P9C9iFWM9K/Y1Qxu3UGMavTP/5i7mn1fLWA/OQIC5bwCn0RoVZo1nlLhD51huVEoIEqJCiUNSg9Dno4cEw7g36v8N+HwbHF/2zo97RPz03YDP53Ih9WE53NqjfYlCRgkkglKhG18HQTLReWNXCaiHsZJ/AyMytBEeYL+xjSypgxOHhsla+z6ezLNVFUsD5b7/MPP1KGKtQWfjg1ei5U+M8zX1BGA8Ro07W9aZpUvjChS02EU8AEyyTsIpjpGizOftZMgM9LQsNZZFfJp2EixMkhZdpbm5kIaLEycz+12yU3d/lP2Kd5ypNyslQta6wC14J4QR19N0kpidUxJyghll5k/yg35+ySro5cT8pEziYepdyNz9WaMc3pS+ccjPutEw1nPQ++RYfR0LGthzUjHymrSTCVel6qVPkN395lxDm6I/eNC+T+//0DNIEBvmtLqbJ9D5xQjebGY8whZd3M29lIDW5JGDXEKHQwVVT8ChISepd46E96rCUqxaAw08E+4JEogXk+NIENnXzbVMat3kL0z3M9yj2zuA2r2HWDZDadvxZK8OG2cSR86stpH1mroVQlXgiMo8W/eFivNIhru0sbdosNc1oRc/+lvllSL1BfnG55fxqBLD5RTvIr2aQ7LbQ3TYnWxd8SdJGA48cewA3knL+SNJqvAFJharpvXL8adkW+EbbAtv2ttAIYGnLOqBtM8hPQNtGA7ulLX1SW+mGtZXXtZW/UlvX61H5BFO+hrmWYmYTFYpt75TKpakYUYXReupOr+FknOZuJyQ3dEFsFyuxbEWPTaN5DRt1368HhNuTBSaPEanGzhGhVNhobLRk+wkGlu2bb2duGWHBt8YIxkkXAC2JWScHZ3UkqqF7IDDQcLVsIIFJJOHlvTor6tmoSG4TQ2EY5lflPCm0Dc9Az8q73JxZS32djbW5wS7M53OUPirM9Qhd5hM0Ksy7w2z8Rwkf9QgI8v5oKXCVgRvacvLvGIH3BsbUprjGXW6o/wNpaKj0CmVuZHN0cmVhbQplbmRvYmoKMSAwIG9iago8PC9UYWJzL1MvR3JvdXA8PC9TL1RyYW5zcGFyZW5jeS9UeXBlL0dyb3VwL0NTL0RldmljZVJHQj4+L0NvbnRlbnRzIDUgMCBSL1R5cGUvUGFnZS9SZXNvdXJjZXM8PC9Db2xvclNwYWNlPDwvQ1MvRGV2aWNlUkdCPj4vUHJvY1NldCBbL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSV0vRm9udDw8L0YxIDIgMCBSL0YyIDMgMCBSL0YzIDQgMCBSPj4+Pi9QYXJlbnQgNiAwIFIvTWVkaWFCb3hbMCAwIDU5NSA4NDJdPj4KZW5kb2JqCjcgMCBvYmoKWzEgMCBSL1hZWiAwIDg1MiAwXQplbmRvYmoKMiAwIG9iago8PC9TdWJ0eXBlL1R5cGUxL1R5cGUvRm9udC9CYXNlRm9udC9IZWx2ZXRpY2EvRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjMgMCBvYmoKPDwvU3VidHlwZS9UeXBlMS9UeXBlL0ZvbnQvQmFzZUZvbnQvSGVsdmV0aWNhLUJvbGQvRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjQgMCBvYmoKPDwvU3VidHlwZS9UeXBlMS9UeXBlL0ZvbnQvQmFzZUZvbnQvSGVsdmV0aWNhLU9ibGlxdWUvRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjYgMCBvYmoKPDwvS2lkc1sxIDAgUl0vVHlwZS9QYWdlcy9Db3VudCAxL0lUWFQoMi4xLjcpPj4KZW5kb2JqCjggMCBvYmoKPDwvTmFtZXNbKEpSX1BBR0VfQU5DSE9SXzBfMSkgNyAwIFJdPj4KZW5kb2JqCjkgMCBvYmoKPDwvRGVzdHMgOCAwIFI+PgplbmRvYmoKMTAgMCBvYmoKPDwvTmFtZXMgOSAwIFIvVHlwZS9DYXRhbG9nL1BhZ2VzIDYgMCBSL1ZpZXdlclByZWZlcmVuY2VzPDwvUHJpbnRTY2FsaW5nL0FwcERlZmF1bHQ+Pj4+CmVuZG9iagoxMSAwIG9iago8PC9Nb2REYXRlKEQ6MjAyMDA0MDIxNjM0MjAtMDMnMDAnKS9DcmVhdG9yKEphc3BlclJlcG9ydHMgTGlicmFyeSB2ZXJzaW9uIDYuMTAuMC1kZGRkMzgyMThhM2M0MDRkMDFlZWNkYjlkOWE3NjM2ZmUyZDAyZDdhKS9DcmVhdGlvbkRhdGUoRDoyMDIwMDQwMjE2MzQyMC0wMycwMCcpL1Byb2R1Y2VyKGlUZXh0IDIuMS43IGJ5IDFUM1hUKT4+CmVuZG9iagp4cmVmCjAgMTIKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwOTkwIDAwMDAwIG4gCjAwMDAwMDEyODQgMDAwMDAgbiAKMDAwMDAwMTM3MiAwMDAwMCBuIAowMDAwMDAxNDY1IDAwMDAwIG4gCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMTU2MSAwMDAwMCBuIAowMDAwMDAxMjQ5IDAwMDAwIG4gCjAwMDAwMDE2MjQgMDAwMDAgbiAKMDAwMDAwMTY3OCAwMDAwMCBuIAowMDAwMDAxNzEwIDAwMDAwIG4gCjAwMDAwMDE4MTQgMDAwMDAgbiAKdHJhaWxlcgo8PC9JbmZvIDExIDAgUi9JRCBbPDM2NzYzOTcwOGVmM2I3N2M3YjY5MWVkMzljM2JmNWExPjw1MTU4OTU1NzM4YzYzMmJiOTZjMTJmZGQ5MWQ1MjVhMj5dL1Jvb3QgMTAgMCBSL1NpemUgMTI+PgpzdGFydHhyZWYKMjAyNAolJUVPRgo=\"}";
    			
    }
}
